name: ${project.name}
version: "${project.version}"
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
api-version: "1.20"
softdepend: [Guilds, Factions, mcMMO, Towny]
folia-supported: true
permissions:
  blocklocker.protect:
    description: "Protect containers and doors."
    default: true
  blocklocker.limit.bypass:
    description: "Bypass the protection limit."
    default: op
commands:
  blocklocker:
    description: "Administration commands for BlockLocker."
    usage: "/<command> [reload|limit]"
    aliases: "bl"
