name: ${project.name}
version: ${project.version}
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
api-version: 1.14
softdepend: [Guilds, Factions, mcMMO, Towny]
permissions:
  blocklocker.protect:
    description: "Protect containers and doors."
    default: true
  blocklocker.bypass:
    description: "Bypass someone else's protection."
    default: op
  blocklocker.reload:
    description: "Reload the plugin using /blocklocker reload."
    default: op
  blocklocker.removeother:
    description: "Remove protection with the plugin using /blocklocker remove."
    default: op
  blocklocker.wilderness:
    description: "Place chests in the wilderness (outside of Towny claims)"
    default: true
commands:
  blocklocker:
    description: "Edit a sign on your protection."
    permission: "blocklocker.protect"
    usage: "/<command> <lineNumber> <value>"
    aliases: "bl"
